{
    "port": 8000,

    "server_name": "Potato Annotation Tool",

    "annotation_task_name": "Text Annotation with Potato2",

    # Output directory for annotations - using persistent volume
    "output_annotation_dir": "annotation_output/",

    # Output format for annotations
    "output_annotation_format": "jsonl", 

    # Codebook URL (optional)
    "annotation_codebook_url": "",

    # Data files - you can upload your own data
    "data_files": [
       "project-hub/simple_examples/data/toy-example.csv"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        "context_key": "context"
    },

    "user_config": {
      "allow_all_users": true,
      "users": []
    },

    # Alert time for each instance (in seconds)
    "alert_time_each_instance": 300,

    "annotation_schemes": [      
        {
            "annotation_type": "multiselect",
            "name": "categories", 
            "description": "What categories apply to this text2?",
            "labels": [
               "positive", "negative", "neutral", "question", "request", "complaint"
            ],
            "sequential_key_binding": true            
        }       
    ],

    "html_layout": "default",
    "base_html_template": "default",
    "header_file": "default",
    "site_dir": "default"
}
