{
    "port": 8000,
    "server_name": "Potato Test Server",
    "annotation_task_name": "Test Annotation Task1",
    "output_annotation_dir": "annotation_output/",
    "output_annotation_format": "jsonl", 
    "annotation_codebook_url": "",
    "data_files": [
       "test_data/sample.csv"
    ],
    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        "context_key": "context"
    },
    "user_config": {
      "allow_all_users": true,
      "users": []
    },
    "alert_time_each_instance": 300,
    "annotation_schemes": [      
        {
            "annotation_type": "multiselect",
            "name": "sentiment", 
            "description": "What sentiment categories apply to this text2?",
            "labels": [
               "positive", "negative", "neutral", "question", "request"
            ],
            "sequential_key_binding": true            
        }       
    ],
    "html_layout": "default",
    "base_html_template": "default",
    "header_file": "default",
    "site_dir": "default"
}
